version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - db
    networks:
      messenger_net:
        ipv4_address: 172.16.239.14

  server:
    build: server/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      messenger_net:
        ipv4_address: 172.16.239.15

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    volumes:
      - db-messages:/db
    networks:
      messenger_net:
        ipv4_address: 172.16.239.16
  
  web:
    build: client/
    ports:
      - 8080:3000
    depends_on:
      - server
    networks:
      messenger_net:
        ipv4_address: 172.16.239.17

volumes:
  db-messages:

networks:
  messenger_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"